sudo: required
language: python
services:
  - docker
install:
  - echo "Nothing to install"
jobs:
  include:
    - stage: deploy
      if: branch = master OR branch = develop
      script:
        - docker build --build-arg GITHUB_PAT=$GITHUB_PAT -t openstudio-jupyter:latest .
after_success:
  - ./deploy_docker.sh
